# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

[tools]
wally = "upliftgames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.6.1"
selene = "kampfkarren/selene@0.31.0"
stylua = "JohnnyMorganz/StyLua@2.5.2"
luau-lsp = "JohnnyMorganz/luau-lsp@1.70.1"
lune = "lune-org/lune@0.10.5"
wally-package-types = "JohnnyMorganz/wally-package-types@1.7.0"
